# 📥 Download and Filter NASA GeneLab Omics Datasets

This notebook automates the retrieval and pre‑processing of omics datasets from the NASA GeneLab Open Science Data Repository (OSDR) using the `genelab_utils` package. It supports both incremental and full updates, applies pre‑filters to reduce file size, and writes a manifest of downloaded files.

Author: Peter W. Rose, UC San Diego (pwrose.ucsd@gmail.com)

In [1]:
import os
import pandas as pd
import genelab_utils as gl

pd.set_option("display.max_rows", None)

In [2]:
os.makedirs("../data", exist_ok=True)

In [3]:
MANIFEST_PATH = "../data/manifest.csv" # file to save dataset info

## Incremental vs Full Update
By default, this notebook runs an incremental update. It downloads and preprocesses any new datasets specified in the "technology_types" list below.

If any datasets have been updated, set the "reset" variable to "True" to run a complete update.

The downloaded datasets are saved in the "datasets" directory.

In [4]:
RESET = False # run incremental update
# RESET = True # run a complete update to refresh datasets

In [5]:
info = gl.get_info()
info.head()

,identifier,assay_name,id.sample name,measurement,technology,host_organism,host_strain,material,study.characteristics.material type.term accession number,study.characteristics.organism.term accession number,file.category,file.subcategory,taxonomy
0,OSD-1,OSD-1_transcription-profiling_dna-microarray_A...,Dmel_OR_wo_FLT_infdw-Bbas_Rep1,transcription profiling,DNA microarray,,,Whole Organism,http://purl.obolibrary.org/obo/NCIT_C13413,http://purl.bioontology.org/ontology/NCBITAXON...,GeneLab Processed Microarray Data Files,Differential gene expression analysis,7227
1,OSD-1,OSD-1_transcription-profiling_dna-microarray_A...,Dmel_OR_wo_GC_infdw-Bbas_Rep3,transcription profiling,DNA microarray,,,Whole Organism,http://purl.obolibrary.org/obo/NCIT_C13413,http://purl.bioontology.org/ontology/NCBITAXON...,GeneLab Processed Microarray Data Files,Differential gene expression analysis,7227
2,OSD-1,OSD-1_transcription-profiling_dna-microarray_A...,Dmel_OR_wo_GC_infdw-Bbas_Rep3,transcription profiling,DNA microarray,,,Whole Organism,http://purl.obolibrary.org/obo/NCIT_C13413,http://purl.bioontology.org/ontology/NCBITAXON...,Microarray Data Files,Normalized data,7227
3,OSD-1,OSD-1_transcription-profiling_dna-microarray_A...,Dmel_OR_wo_GC_infdw-Bbas_Rep3,transcription profiling,DNA microarray,,,Whole Organism,http://purl.obolibrary.org/obo/NCIT_C13413,http://purl.bioontology.org/ontology/NCBITAXON...,Microarray Data Files,Raw array data,7227
4,OSD-1,OSD-1_transcription-profiling_dna-microarray_A...,Dmel_OR_wo_GC_infdw-Bbas_Rep3,transcription profiling,DNA microarray,,,Whole Organism,http://purl.obolibrary.org/obo/NCIT_C13413,http://purl.bioontology.org/ontology/NCBITAXON...,GeneLab Processed Microarray Data Files,Raw Data,7227

## Get a List of GeneLab processed Datasets

In [6]:
dataset_info = gl.get_processed_datasets()

## Filter by Technology Type

In [7]:
technology_types = ["RNA Sequencing (RNA-Seq)", 
                    "DNA microarray", 
                    "Whole Genome Bisulfite Sequencing",
                    "Reduced-Representation Bisulfite Sequencing",
                    "16S",
                    "ITS",
                    "18S",
                    "16S and ITS",
                   ]
dataset_info = gl.filter_by_technology_type(dataset_info, technology_types)

## Filter by Organism

In [8]:
print(f"Available organisms: {dataset_info['taxonomy'].dropna().unique()}")

Available organisms: ['7227' '10090' '6239' '3702' '9606' '' '1423' '13613' '287' '131567'
 '1452' '562' '10116' '7955' '15368' '1781' '3711' '63436' '63433' '4932'
 '148447' '104782' '8090']

In [9]:
taxids = {"9606": "Homo sapiens",
          # -- Rodens -- 
          "10090": "Mus musculus",
          "10116": "Rattus norvegicus",
          # -- Fish --
          "7955": "Danio rerio",
          "8090": "Oryzias latipes",
          # -- Nematoda --
          "6239": "Caenorhabditis elegans",
          # -- Insecta --
          "7227": "Drosophila melanogaster",
          "63436": "Leptopilina heterotoma",
          "63433": "Leptopilina boulardi",
          # -- Bacteria --
          "562": "Escherichia coli",
          "287": "Pseudomonas aeruginosa",
          "1423": "Bacillus subtilis",
          "1781": "Mycobacterium marinum",
          "148447": "Paraburkholderia phymatum",
          # -- Fungi --
          "4932": "Saccharomyces cerevisiae",
          # -- Plants --
          "3711": "Brassica rapa",
          "15368": "Brachypodium distachyon",
          "3702": "Arabidopsis thaliana",
          # -- Other --
          "104782": "Adineta vaga",
          "13613": "Microbiota",
          # -- Host organisms
          "4236": "Lactuca sativa",
         }
          
dataset_info = gl.filter_by_organism(dataset_info, taxids)
dataset_info = gl.filter_by_host_organism(dataset_info, taxids)

In [10]:
print(f"Filtered organisms: {dataset_info['taxonomy'].unique()}")

Filtered organisms: ['7227' '10090' '6239' '3702' '9606' '1423' '13613' '287' '562' '10116'
 '7955' '15368' '1781' '3711' '63436' '63433' '4932' '148447' '104782'
 '8090']

In [11]:
dataset_info = dataset_info[["identifier", "technology", "measurement", "assay_name", "taxonomy", "organism", "material", "host_organism", "host_taxonomy", "host_strain"]].copy()
dataset_info.drop_duplicates(inplace=True)
dataset_info.fillna("", inplace=True)
dataset_info.head(1000)

,identifier,technology,measurement,assay_name,taxonomy,organism,material,host_organism,host_taxonomy,host_strain
203,OSD-1,DNA microarray,transcription profiling,OSD-1_transcription-profiling_dna-microarray_A...,7227,Drosophila melanogaster,Whole Organism,,,
290,OSD-100,RNA Sequencing (RNA-Seq),transcription profiling,OSD-100_transcription-profiling_rna-sequencing...,10090,Mus musculus,left eye,,,
298,OSD-101,RNA Sequencing (RNA-Seq),transcription profiling,OSD-101_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left gastrocnemius,,,
287,OSD-102,RNA Sequencing (RNA-Seq),transcription profiling,OSD-102_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left kidney,,,
286,OSD-103,Whole Genome Bisulfite Sequencing,DNA methylation profiling,OSD-103_dna-methylation-profiling_whole-genome...,10090,Mus musculus,Left quadriceps femoris,,,
294,OSD-103,RNA Sequencing (RNA-Seq),transcription profiling,OSD-103_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left quadriceps femoris,,,
308,OSD-104,RNA Sequencing (RNA-Seq),transcription profiling,OSD-104_transcription-profiling_rna-sequencing...,10090,Mus musculus,Soleus-both sides,,,
304,OSD-105,Whole Genome Bisulfite Sequencing,DNA methylation profiling,OSD-105_dna-methylation-profiling_whole-genome...,10090,Mus musculus,Left tibialis anterior,,,
284,OSD-105,RNA Sequencing (RNA-Seq),transcription profiling,OSD-105_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left tibialis anterior,,,
246,OSD-109,DNA microarray,transcription profiling,OSD-109_transcription-profiling_dna-microarray...,10090,Mus musculus,primary left ventricular cell,,,
330,OSD-111,DNA microarray,transcription profiling,OSD-111_transcription-profiling_dna-microarray...,10090,Mus musculus,Soleus,,,
338,OSD-111,DNA microarray,transcription profiling,OSD-111_transcription-profiling_dna-microarray...,10090,Mus musculus,Extensor digitorum longus,,,
331,OSD-112,DNA microarray,transcription profiling,OSD-112_transcription-profiling_dna-microarray...,6239,Caenorhabditis elegans,Whole Organism,,,
404,OSD-113,DNA microarray,transcription profiling,OSD-113_transcription-profiling_dna-microarray,6239,Caenorhabditis elegans,Whole Organism,,,
245,OSD-117,DNA microarray,transcription profiling,OSD-117_transcription-profiling_dna-microarray...,10090,Mus musculus,murine left ventricular cardiomyocytes,,,
94,OSD-120,RNA Sequencing (RNA-Seq),transcription profiling,OSD-120_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,,,,
391,OSD-121,DNA microarray,transcription profiling,OSD-121_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,,,,
401,OSD-124,DNA microarray,transcription profiling,OSD-124_transcription-profiling_dna-microarray...,9606,Homo sapiens,,,,
346,OSD-125,DNA microarray,transcription profiling,OSD-125_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
393,OSD-127,RNA Sequencing (RNA-Seq),transcription profiling,OSD-127_transcription-profiling_rna-sequencing...,9606,Homo sapiens,,,,
184,OSD-129,DNA microarray,transcription profiling,OSD-129_transcription-profiling_dna-microarray...,9606,Homo sapiens,Human Peripheral blood lymphocytes (PBL),,,
329,OSD-13,DNA microarray,transcription profiling,OSD-13_transcription-profiling_dna-microarray_...,9606,Homo sapiens,Primary T Cells,,,
170,OSD-135,DNA microarray,transcription profiling,OSD-135_transcription-profiling_dna-microarray...,10090,Mus musculus,,,,
341,OSD-136,DNA microarray,transcription profiling,OSD-136_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,,,,
207,OSD-137,RNA Sequencing (RNA-Seq),transcription profiling,OSD-137_transcription-profiling_rna-sequencing...,10090,Mus musculus,Liver,,,
204,OSD-138,RNA Sequencing (RNA-Seq),transcription profiling,OSD-138_transcription-profiling_rna-sequencing...,1423,Bacillus subtilis,Cells,,,
425,OSD-141,RNA Sequencing (RNA-Seq),transcription profiling,OSD-141_transcription-profiling_rna-sequencing...,10090,Mus musculus,Whole Spleen,,,
440,OSD-141,RNA Sequencing (RNA-Seq),transcription profiling,OSD-141_transcription-profiling_rna-sequencing...,10090,Mus musculus,Cells,,,
443,OSD-141,RNA Sequencing (RNA-Seq),transcription profiling,OSD-141_transcription-profiling_rna-sequencing...,10090,Mus musculus,Tissue,,,
18,OSD-146,16S,amplicon sequencing,OSD-146_amplicon-sequencing_16s_Illumina,13613,Microbiota,Feces,Mus musculus,10090,C57BL/6J
209,OSD-147,DNA microarray,transcription profiling,OSD-147_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,hypocotyl cell culture,,,
350,OSD-15,DNA microarray,transcription profiling,OSD-15_transcription-profiling_dna-microarray_...,287,Pseudomonas aeruginosa,Cells,,,
120,OSD-151,DNA microarray,transcription profiling,OSD-151_transcription-profiling_dna-microarray...,9606,Homo sapiens,3D cells,,,
56,OSD-152,DNA microarray,transcription profiling,OSD-152_transcription-profiling_dna-microarray...,9606,Homo sapiens,Peripheral blood cell,,,
214,OSD-153,DNA microarray,transcription profiling,OSD-153_transcription-profiling_dna-microarray...,10090,Mus musculus,whole 4th (inguinal) mammary glands,,,
109,OSD-154,DNA microarray,transcription profiling,OSD-154_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
15,OSD-155,DNA microarray,transcription profiling,OSD-155_transcription-profiling_dna-microarray...,9606,Homo sapiens,Whole Blood,,,
26,OSD-157,DNA microarray,transcription profiling,OSD-157_transcription-profiling_dna-microarray...,9606,Homo sapiens,Whole Blood,,,
273,OSD-160,DNA microarray,transcription profiling,OSD-160_transcription-profiling_dna-microarray...,10090,Mus musculus,4T1 tumor,,,
248,OSD-161,RNA Sequencing (RNA-Seq),transcription profiling,OSD-161_transcription-profiling_rna-sequencing...,10090,Mus musculus,Adrenal gland,,,
243,OSD-162,RNA Sequencing (RNA-Seq),transcription profiling,OSD-162_transcription-profiling_rna-sequencing...,10090,Mus musculus,eye,,,
208,OSD-163,RNA Sequencing (RNA-Seq),transcription profiling,OSD-163_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left kidney,,,
389,OSD-164,RNA Sequencing (RNA-Seq),transcription profiling,OSD-164_transcription-profiling_rna-sequencing...,10090,Mus musculus,Liver,,,
406,OSD-164,RNA Sequencing (RNA-Seq),transcription profiling,OSD-164_transcription-profiling_rna-sequencing...,10090,Mus musculus,Spleen,,,
51,OSD-168,RNA Sequencing (RNA-Seq),transcription profiling,OSD-168_transcription-profiling_rna-sequencing...,10090,Mus musculus,Liver,,,
165,OSD-17,DNA microarray,transcription profiling,OSD-17_transcription-profiling_dna-microarray_...,3702,Arabidopsis thaliana,,,,
154,OSD-172,DNA microarray,transcription profiling,OSD-172_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
405,OSD-173,RNA Sequencing (RNA-Seq),transcription profiling,pmj150512_transcription_profiling_RNA_Sequenci...,10090,Mus musculus,liver,,,
28,OSD-178,DNA microarray,transcription profiling,OSD-178_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
269,OSD-182,DNA microarray,transcription profiling,OSD-182_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
54,OSD-183,DNA microarray,transcription profiling,OSD-183_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
84,OSD-188,DNA microarray,transcription profiling,OSD-188_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
150,OSD-189,DNA microarray,transcription profiling,OSD-189_transcription-profiling_dna-microarray...,9606,Homo sapiens,Cells,,,
5,OSD-191,16S,amplicon sequencing,OSD-191_amplicon-sequencing_16s_illumina,13613,Microbiota,Feces,Homo sapiens,9606,
326,OSD-194,RNA Sequencing (RNA-Seq),transcription profiling,OSD-194_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left retina,,,
414,OSD-194,RNA Sequencing (RNA-Seq),transcription profiling,OSD-194_transcription-profiling_rna-sequencing...,10090,Mus musculus,Right retina,,,
442,OSD-200,16S and ITS,Amplicon Sequencing,OSD-200_amplicon-sequencing_16s-and-its_Illumina,562,Escherichia coli,blank,,,
102,OSD-201,RNA Sequencing (RNA-Seq),transcription profiling,OSD-201_transcription-profiling_rna-sequencing...,10090,Mus musculus,Spleen,,,
79,OSD-202,RNA Sequencing (RNA-Seq),transcription profiling,OSD-202_transcription-profiling_rna-sequencing...,10090,Mus musculus,brain,,,
39,OSD-203,RNA Sequencing (RNA-Seq),transcription profiling,OSD-203_transcription-profiling_rna-sequencing...,10090,Mus musculus,Retina,,,
228,OSD-205,DNA microarray,transcription profiling,OSD-205_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,,,,
99,OSD-207,RNA Sequencing (RNA-Seq),transcription profiling,OSD-207_transcription-profiling_rna-sequencing...,7227,Drosophila melanogaster,Head,,,
399,OSD-208,DNA microarray,transcription profiling,OSD-208_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,,,,
397,OSD-208,RNA Sequencing (RNA-Seq),transcription profiling,OSD-208_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,,,,
230,OSD-21,DNA microarray,transcription profiling,OSD-21_transcription-profiling_dna-microarray_...,10090,Mus musculus,calf muscle,,,
372,OSD-21,DNA microarray,transcription profiling,OSD-21_transcription-profiling_dna-microarray_...,10090,Mus musculus,Gastrocnemius,,,
176,OSD-211,RNA Sequencing (RNA-Seq),transcription profiling,OSD-211_transcription-profiling_rna-sequencing...,10090,Mus musculus,Spleen,,,
394,OSD-213,DNA microarray,transcription profiling,OSD-213_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,callus cell culture,,,
142,OSD-214,RNA Sequencing (RNA-Seq),transcription profiling,OSD-214_transcription-profiling_rna-sequencing...,10090,Mus musculus,Bone Marrow,,,
97,OSD-218,RNA Sequencing (RNA-Seq),transcription profiling,OSD-218_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,,,,
188,OSD-22,DNA microarray,transcription profiling,OSD-22_transcription-profiling_dna-microarray_...,3702,Arabidopsis thaliana,Plant Roots,,,
81,OSD-223,RNA Sequencing (RNA-Seq),transcription profiling,OSD-223_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,,,,
27,OSD-235,RNA Sequencing (RNA-Seq),transcription profiling,OSD-235_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left Lobe of the Liver,,,
34,OSD-236,RNA Sequencing (RNA-Seq),transcription profiling,freezing_study_quad_transcription_profiling_RN...,10090,Mus musculus,Left quadriceps femoris,,,
175,OSD-237,RNA Sequencing (RNA-Seq),transcription profiling,OSD-237_transcription-profiling_rna-sequencing...,10090,Mus musculus,dorsal skin,,,
146,OSD-238,RNA Sequencing (RNA-Seq),transcription profiling,OSD-238_transcription-profiling_rna-sequencing...,10090,Mus musculus,dorsal skin,,,
171,OSD-239,RNA Sequencing (RNA-Seq),transcription profiling,OSD-239_transcription-profiling_rna-sequencing...,10090,Mus musculus,femoral skin,,,
190,OSD-240,RNA Sequencing (RNA-Seq),transcription profiling,OSD-240_transcription-profiling_rna-sequencing...,10090,Mus musculus,dorsal skin,,,
194,OSD-241,RNA Sequencing (RNA-Seq),transcription profiling,OSD-241_transcription-profiling_rna-sequencing...,10090,Mus musculus,femoral lateral skin,,,
167,OSD-242,RNA Sequencing (RNA-Seq),transcription profiling,OSD-242_transcription-profiling_rna-sequencing...,10090,Mus musculus,Liver,,,
50,OSD-243,RNA Sequencing (RNA-Seq),transcription profiling,OSD-243_transcription-profiling_rna-sequencing...,10090,Mus musculus,dorsal skin,,,
43,OSD-244,RNA Sequencing (RNA-Seq),transcription profiling,OSD-244_transcription-profiling_rna-sequencing...,10090,Mus musculus,Thymus,,,
40,OSD-245,RNA Sequencing (RNA-Seq),transcription profiling,OSD-245_transcription-profiling_rna-sequencing...,10090,Mus musculus,Liver,,,
69,OSD-246,RNA Sequencing (RNA-Seq),transcription profiling,OSD-246_transcription-profiling_rna-sequencing...,10090,Mus musculus,Spleen,,,
47,OSD-247,RNA Sequencing (RNA-Seq),transcription profiling,OSD-247_transcription-profiling_rna-sequencing...,10090,Mus musculus,descending colon,,,
41,OSD-248,RNA Sequencing (RNA-Seq),transcription profiling,OSD-248_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left Lung,,,
212,OSD-25,DNA microarray,transcription profiling,OSD-25_transcription-profiling_dna-microarray_...,10090,Mus musculus,Liver,,,
179,OSD-251,RNA Sequencing (RNA-Seq),transcription profiling,OSD-251_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,Seedlings,,,
8,OSD-253,RNA Sequencing (RNA-Seq),transcription profiling,OSD-253_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left kidney,,,
20,OSD-254,RNA Sequencing (RNA-Seq),transcription profiling,rr7_skn_transcription_profiling_RNA_Sequencing...,10090,Mus musculus,dorsal skin,,,
227,OSD-255,RNA Sequencing (RNA-Seq),transcription profiling,OSD-255_transcription-profiling_rna-sequencing...,10090,Mus musculus,Right retina,,,
206,OSD-258,RNA Sequencing (RNA-Seq),transcription profiling,OSD-258_transcription-profiling_rna-sequencing...,9606,Homo sapiens,Cells,,,
311,OSD-267,16S,Amplicon Sequencing,OSD-267_amplicon-sequencing_16s_illumina,13613,Microbiota,,Lactuca sativa,4236,Outredgeous
281,OSD-267,ITS,Amplicon Sequencing,OSD-267_amplicon-sequencing_its_illumina,13613,Microbiota,,Lactuca sativa,4236,Outredgeous
336,OSD-268,16S,Amplicon Sequencing,OSD-268_amplicon-sequencing_16s_illumina,13613,Microbiota,leaf,Lactuca sativa,4236,Outredgeous
419,OSD-268,16S,Amplicon Sequencing,OSD-268_amplicon-sequencing_16s_illumina,13613,Microbiota,root,Lactuca sativa,4236,Outredgeous
335,OSD-268,ITS,Amplicon Sequencing,OSD-268_amplicon-sequencing_its_illumina,13613,Microbiota,leaf,Lactuca sativa,4236,Outredgeous
420,OSD-268,ITS,Amplicon Sequencing,OSD-268_amplicon-sequencing_its_illumina,13613,Microbiota,root,Lactuca sativa,4236,Outredgeous
250,OSD-269,16S,Amplicon Sequencing,OSD-269_amplicon-sequencing_16s_illumina,13613,Microbiota,,Lactuca sativa,4236,cv. Outredgeous
49,OSD-27,DNA microarray,transcription profiling,OSD-27_transcription-profiling_dna-microarray_...,7227,Drosophila melanogaster,Whole Organism,,,
411,OSD-270,RNA Sequencing (RNA-Seq),transcription profiling,OSD-270_transcription-profiling_rna-sequencing...,10090,Mus musculus,Heart,,,
193,OSD-271,DNA microarray,transcription profiling,OSD-271_transcription-profiling_dna-microarray,10116,Rattus norvegicus,mammary gland,,,
42,OSD-272,RNA Sequencing (RNA-Seq),transcription profiling,rapid_freeze_spleen_transcription_profiling_RN...,10090,Mus musculus,Spleen,,,
35,OSD-273,RNA Sequencing (RNA-Seq),transcription profiling,rapid_freeze_liver_transcription_profiling_RNA...,10090,Mus musculus,liver,,,
271,OSD-278,RNA Sequencing (RNA-Seq),transcription profiling,OSD-278_transcription-profiling_rna-sequencing...,7227,Drosophila melanogaster,Whole Organism,,,
101,OSD-281,RNA Sequencing (RNA-Seq),transcription profiling,OSD-281_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,,,,
369,OSD-282,DNA microarray,transcription profiling,OSD-282_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,Seedlings,,,
340,OSD-288,RNA Sequencing (RNA-Seq),transcription profiling,OSD-288_transcription-profiling_rna-sequencing...,10090,Mus musculus,Spleen,,,
205,OSD-289,RNA Sequencing (RNA-Seq),transcription profiling,OSD-289_transcription-profiling_rna-sequencing...,10090,Mus musculus,thymus,,,
361,OSD-29,DNA microarray,transcription profiling,OSD-29_transcription-profiling_dna-microarray_...,10090,Mus musculus,,,,
113,OSD-294,RNA Sequencing (RNA-Seq),transcription profiling,OSD-294_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left Lobe of the Liver,,,
91,OSD-295,RNA Sequencing (RNA-Seq),transcription profiling,OSD-295_transcription-profiling_rna-sequencing...,10090,Mus musculus,Soleus,,,
90,OSD-296,DNA microarray,transcription profiling,OSD-296_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,,,,
211,OSD-3,DNA microarray,transcription profiling,OSD-3_transcription-profiling_dna-microarray_a...,7227,Drosophila melanogaster,Whole Organism,,,
375,OSD-30,DNA microarray,transcription profiling,OSD-30_transcription-profiling_dna-microarray_...,10090,Mus musculus,Cells,,,
151,OSD-304,DNA microarray,transcription profiling,OSD-304_transcription-profiling_dna-microarray,10090,Mus musculus,Blood,,,
373,OSD-308,RNA Sequencing (RNA-Seq),transcription profiling,OSD-308_transcription-profiling_rna-sequencing...,10090,Mus musculus,Zygote,,,
210,OSD-313,RNA Sequencing (RNA-Seq),transcription profiling,OSD-313_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,,,,
213,OSD-314,RNA Sequencing (RNA-Seq),transcription profiling,OSD-314_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,Seedlings,,,
70,OSD-320,DNA microarray,transcription profiling,OSD-320_transcription-profiling_dna-microarray...,3702,Arabidopsis thaliana,Seedlings,,,
71,OSD-321,RNA Sequencing (RNA-Seq),transcription profiling,OSD-321_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,Seedlings,,,
36,OSD-322,RNA Sequencing (RNA-Seq),transcription profiling,OSD-322_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left lobe of liver,,,
370,OSD-323,RNA Sequencing (RNA-Seq),transcription profiling,OSD-323_transcription-profiling_rna-sequencing...,9606,Homo sapiens,Cells,,,
357,OSD-326,RNA Sequencing (RNA-Seq),transcription profiling,OSD-326_transcription-profiling_rna-sequencing...,10090,Mus musculus,Quadriceps femoris,,,
426,OSD-331,RNA Sequencing (RNA-Seq),transcription profiling,OSD-331_transcription-profiling_rna-sequencing...,9606,Homo sapiens,Cells,,,
55,OSD-34,DNA microarray,transcription profiling,OSD-34_transcription-profiling_dna-microarray_...,7227,Drosophila melanogaster,Whole Organism,,,
88,OSD-346,RNA Sequencing (RNA-Seq),transcription profiling,OSD-346_transcription-profiling_rna-sequencing...,3702,Arabidopsis thaliana,,,,
259,OSD-347,RNA Sequencing (RNA-Seq),transcription profiling,OSD-347_transcription-profiling_rna-sequencing...,7227,Drosophila melanogaster,Heart,,,
407,OSD-35,DNA microarray,transcription profiling,OSD-35_transcription-profiling_dna-microarray_...,6239,Caenorhabditis elegans,,,,
380,OSD-352,RNA Sequencing (RNA-Seq),transcription profiling,OSD-352_transcription-profiling_rna-sequencing...,10090,Mus musculus,Brain,,,
178,OSD-36,DNA microarray,transcription profiling,OSD-36_transcription-profiling_dna-microarray_...,7227,Drosophila melanogaster,,,,
219,OSD-367,DNA microarray,transcription profiling,OSD-367_transcription-profiling_dna-microarray...,9606,Homo sapiens,3D Cells,,,
299,OSD-368,DNA microarray,transcription profiling,OSD-368_transcription-profiling_microarray,9606,Homo sapiens,3D cells,,,
383,OSD-369,DNA microarray,transcription profiling,OSD-369_transcription-profiling_microarray,9606,Homo sapiens,3D cells,,,
44,OSD-37,RNA Sequencing (RNA-Seq),transcription profiling,OSD-37_transcription-profiling_rna-sequencing-...,3702,Arabidopsis thaliana,Seedlings,,,
38,OSD-370,DNA microarray,transcription profiling,OSD-370_transcription-profiling_dna-microarray...,9606,Homo sapiens,Vastus Lateralis,,,
300,OSD-373,RNA Sequencing (RNA-Seq),transcription profiling,OSD-373_transcription-profiling_rna-sequencing...,7955,Danio rerio,embryo,,,
225,OSD-374,RNA Sequencing (RNA-Seq),transcription profiling,OSD-374_transcription-profiling_rna-sequencing...,10090,Mus musculus,Hippocampus,,,
59,OSD-375,RNA Sequencing (RNA-Seq),transcription profiling,GLDS-375_transcription-profiling_rna-sequencin...,15368,Brachypodium distachyon,,,,
7,OSD-379,RNA Sequencing (RNA-Seq),transcription profiling,OSD-379_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left Lobe of the Liver,,,
301,OSD-38,RNA Sequencing (RNA-Seq),transcription profiling,OSD-38_transcription-profiling_rna-sequencing-...,3702,Arabidopsis thaliana,,,,
11,OSD-385,16S,Amplicon Sequencing,OSD-385_amplicon-sequencing_16s_illumina,13613,Microbiota,,Lactuca sativa,4236,Outredgeous

## Select Datasets to Download
The map below specifies the technology type and a substring used to identify processed files. Processed files must contain this substring.

In [12]:
file_types = {"DNA microarray": "differential_expression",
              "RNA Sequencing (RNA-Seq)": "differential_expression",
              "Whole Genome Bisulfite Sequencing": "differential_methylation_tiles",
              "Reduced-Representation Bisulfite Sequencing": "differential_methylation_tiles",
              "16S": "differential_abundance",
              "ITS": "differential_abundance",
              "18S": "differential_abundance",
              "16S and ITS": "differential_abundance",
              }

#### Define pre-filters to reduce the file the essential data

In [13]:
def differential_expression_filter(df, threshold=0.1):
    if "ENTREZID" not in df.columns:
        return pd.DataFrame()
        
    filtered_df = df[df['ENTREZID'].notna() & (df['ENTREZID'].astype(str) != '')]
    # Keep only required columns
    filtered_df = filtered_df.filter(regex=r"^(ENTREZID|SYMBOL|GENENAME|Log2fc_|Adj\.p\.value_)")
    adj_pval_cols = [col for col in filtered_df.columns if col.startswith("Adj.p.value_")]
    filtered_df = filtered_df[filtered_df[adj_pval_cols].le(threshold).any(axis=1)]
    # Explode rows with multiple genes
    if "ENTREZID" in filtered_df.columns:
        filtered_df["ENTREZID"] = filtered_df["ENTREZID"].astype(str)
        filtered_df["ENTREZID"] = filtered_df["ENTREZID"].apply(lambda x:x.split('|'))
        filtered_df = filtered_df.explode('ENTREZID')
        filtered_df["ENTREZID"] = filtered_df["ENTREZID"].str.strip()
    filtered_df["differential_analysis_method"] = "DESeq2"
    return filtered_df

In [14]:
def differential_methylation_filter(df, threshold=0.1):
    # add reversed contrast:
    #    meth.diff_(Ground Control)v(Space Flight) -> meth.diff_(Space Flight)v(Ground Control) and reverse sign
    #    qvalue_(Ground Control)v(Space Flight) -> qvalue_(Space Flight)v(Ground Control)
    df = gl.add_reversed_contrast_columns(df)
    
    filtered_df = df[df['ENTREZID'].notna() & (df['ENTREZID'].astype(str) != '')]
    # Keep only required columns
    filtered_df = filtered_df.filter(regex=r"^(ENTREZID|SYMBOL|GENENAME|chr|start|end|dist.to.feature|prom|exon|intron|meth.diff_|qvalue_)")
    qval_cols = [col for col in filtered_df.columns if col.startswith("qvalue_")]
    filtered_df = filtered_df[filtered_df[qval_cols].le(threshold).any(axis=1)]
     # Explode rows with multiple genes
    if "ENTREZID" in filtered_df.columns:
        filtered_df["ENTREZID"] = filtered_df["ENTREZID"].astype(str)
        filtered_df["ENTREZID"] = filtered_df["ENTREZID"].apply(lambda x:x.split('|'))
        filtered_df = filtered_df.explode('ENTREZID')
        filtered_df["ENTREZID"] = filtered_df["ENTREZID"].str.strip()
    return filtered_df

In [15]:
def differential_abundance_filter(df, threshold=0.1):
    s = df["NCBI_id"]

    mask = (
            s.notna()                               # real NaNs
            & s.astype(str).str.strip().ne("")      # empty/whitespace
            & s.astype(str).str.strip().str.lower().ne("nan")  # literal "nan"
    )        

    filtered_df = df[mask].copy()
    filtered_df["NCBI_id"] = filtered_df["NCBI_id"].astype(int)

    # Keep only required columns
    filtered_df = filtered_df.filter(regex=r"^(best_taxonomy|NCBI_id|Lnfc_|Log2fc_|Q\.value_|Adj\.p\.value_)")
    adj_pval_cols = [col for col in filtered_df.columns if col.startswith("Adj.p.value_")]
    if len(adj_pval_cols) > 0:
        filtered_df = filtered_df[filtered_df[adj_pval_cols].le(threshold).any(axis=1)]
    qval_cols = [col for col in filtered_df.columns if col.startswith("Q.value_")]
    if len(qval_cols) > 0:
        filtered_df = filtered_df[filtered_df[qval_cols].le(threshold).any(axis=1)]

    return filtered_df

In [16]:
filters = {"differential_expression": differential_expression_filter,
           "differential_methylation_tiles": differential_methylation_filter,
           "differential_abundance": differential_abundance_filter,}

In [17]:
manifest = gl.download_data_files(dataset_info, file_types, filters, reset=RESET)
manifest.to_csv(MANIFEST_PATH, index=False)

File already exist: GLDS-1_array_differential_expression.csv
File already exist: GLDS-100_rna_seq_differential_expression.csv
File already exist: GLDS-101_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-102_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-103_Gwgbs_differential_methylation_tiles_GLMethylSeq.csv
File already exist: GLDS-103_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-104_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-105_Gwgbs_differential_methylation_tiles_GLMethylSeq.csv
File already exist: GLDS-105_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-109_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-112_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-113_array_differential_expression.csv
File already exist: GLDS-117_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-120_rna_seq_differential_expression.csv
File already exist: GLDS-121_array_differential_expression_GLmicroarray.csv
Downloading: GLDS-124_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-124_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-125_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-127_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-129_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-13_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-136_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-137_rna_seq_differential_expression.csv
Downloading: GLDS-138_rna_seq_differential_expression_GLbulkRNAseq.csv
Skipping file: GLDS-138_rna_seq_differential_expression_GLbulkRNAseq.csv. No data after filtering.
File already exist: GLDS-141_rna_seq_differential_expression.csv
File already exist: GLDS-141_rna_seq_differential_expression.csv
File already exist: GLDS-141_rna_seq_differential_expression.csv
File already exist: GLDS-147_array_differential_expression.csv
Downloading: GLDS-15_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-15_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-151_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-152_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-153_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-154_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-155_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-157_array_differential_expression_G4112F_GLmicroarray.csv
File already exist: GLDS-157_array_differential_expression_G4112A_GLmicroarray.csv
File already exist: GLDS-160_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-161_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-162_rna_seq_differential_expression.csv
File already exist: GLDS-163_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-168_rna_seq_differential_expression.csv
File already exist: GLDS-172_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-173_rna_seq_differential_expression.csv
File already exist: GLDS-178_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-182_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-183_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-188_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-189_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-194_rna_seq_differential_expression.csv
File already exist: GLDS-194_rna_seq_differential_expression.csv
File already exist: GLDS-201_rna_seq_differential_expression.csv
File already exist: GLDS-202_rna_seq_differential_expression.csv
File already exist: GLDS-203_rna_seq_differential_expression.csv
File already exist: GLDS-205_array_differential_expression.csv
File already exist: GLDS-207_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-208_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-208_array_differential_expression.csv
File already exist: GLDS-208_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-208_array_differential_expression.csv
File already exist: GLDS-211_rna_seq_differential_expression.csv
File already exist: GLDS-213_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-214_rna_seq_differential_expression.csv
File already exist: GLDS-218_rna_seq_differential_expression.csv
File already exist: GLDS-22_array_differential_expression.csv
File already exist: GLDS-235_rna_seq_differential_expression.csv
File already exist: GLDS-236_rna_seq_differential_expression.csv
File already exist: GLDS-237_rna_seq_differential_expression.csv
File already exist: GLDS-238_rna_seq_differential_expression.csv
File already exist: GLDS-239_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-240_rna_seq_differential_expression.csv
File already exist: GLDS-241_rna_seq_differential_expression.csv
File already exist: GLDS-242_rna_seq_differential_expression.csv
File already exist: GLDS-243_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-244_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-245_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-246_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-247_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-248_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-25_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-251_rna_seq_differential_expression.csv
File already exist: GLDS-253_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-254_rna_seq_differential_expression.csv
File already exist: GLDS-255_rna_seq_differential_expression.csv
File already exist: GLDS-258_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-267_GAmplicon_deseq2_differential_abundance_ITS_GLAmpSeq.csv
Downloading: GLDS-267_GAmplicon_ancombc2_differential_abundance_ITS_GLAmpSeq.csv
Skipping file: GLDS-267_GAmplicon_ancombc2_differential_abundance_ITS_GLAmpSeq.csv. No data after filtering.
File already exist: GLDS-267_GAmplicon_ancombc1_differential_abundance_ITS_GLAmpSeq.csv
File already exist: GLDS-267_GAmplicon_deseq2_differential_abundance_16S_GLAmpSeq.csv
Downloading: GLDS-267_GAmplicon_ancombc2_differential_abundance_16S_GLAmpSeq.csv
Skipping file: GLDS-267_GAmplicon_ancombc2_differential_abundance_16S_GLAmpSeq.csv. No data after filtering.
File already exist: GLDS-267_GAmplicon_ancombc1_differential_abundance_16S_GLAmpSeq.csv
File already exist: GLDS-267_GAmplicon_deseq2_differential_abundance_ITS_GLAmpSeq.csv
Downloading: GLDS-267_GAmplicon_ancombc2_differential_abundance_ITS_GLAmpSeq.csv
Skipping file: GLDS-267_GAmplicon_ancombc2_differential_abundance_ITS_GLAmpSeq.csv. No data after filtering.
File already exist: GLDS-267_GAmplicon_ancombc1_differential_abundance_ITS_GLAmpSeq.csv
File already exist: GLDS-267_GAmplicon_deseq2_differential_abundance_16S_GLAmpSeq.csv
Downloading: GLDS-267_GAmplicon_ancombc2_differential_abundance_16S_GLAmpSeq.csv
Skipping file: GLDS-267_GAmplicon_ancombc2_differential_abundance_16S_GLAmpSeq.csv. No data after filtering.
File already exist: GLDS-267_GAmplicon_ancombc1_differential_abundance_16S_GLAmpSeq.csv
File already exist: GLDS-27_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-270_rna_seq_differential_expression.csv
File already exist: GLDS-271_array_differential_expression.csv
File already exist: GLDS-272_rna_seq_differential_expression.csv
File already exist: GLDS-273_rna_seq_differential_expression.csv
File already exist: GLDS-278_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-281_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-282_array_differential_expression.csv
File already exist: GLDS-288_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-289_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-294_rna_seq_differential_expression.csv
File already exist: GLDS-295_rna_seq_differential_expression.csv
File already exist: GLDS-296_array_differential_expression.csv
File already exist: GLDS-3_array_differential_expression_GLmicroarray.csv
Downloading: GLDS-30_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-30_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-304_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-308_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-313_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-314_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-320_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-321_rna_seq_differential_expression.csv
File already exist: GLDS-322_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-323_rna_seq_differential_expression.csv
File already exist: GLDS-326_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-34_array_differential_expression_GLmicroarray.csv
Downloading: GLDS-346_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-347_rna_seq_differential_expression.csv
Downloading: GLDS-352_rna_seq_differential_expression.csv
File already exist: GLDS-36_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-367_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-368_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-369_array_differential_expression_GLmicroarray.csv
Downloading: GLDS-37_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-370_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-373_rna_seq_differential_expression_GLbulkRNAseq.csv
Downloading: GLDS-374_rna_seq_differential_expression_GLbulkRNAseq.csv
Skipping file: GLDS-374_rna_seq_differential_expression_GLbulkRNAseq.csv. No data after filtering.
File already exist: GLDS-379_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-38_rna_seq_differential_expression.csv
File already exist: GLDS-397_rna_seq_differential_expression.csv
File already exist: GLDS-397_rna_seq_differential_expression.csv
File already exist: GLDS-4_array_differential_expression.csv
File already exist: GLDS-406_rna_seq_differential_expression.csv
File already exist: GLDS-418_rna_seq_differential_expression.csv
File already exist: GLDS-419_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-42_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-420_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-421_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-422_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-423_rna_seq_differential_expression.csv
File already exist: GLDS-425_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-426_rna_seq_differential_expression.csv
File already exist: GLDS-427_rna_seq_differential_expression.csv
File already exist: GLDS-427_rna_seq_differential_expression.csv
File already exist: GLDS-428_array_differential_expression.csv
Downloading: GLDS-43_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-43_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-431_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-434_array_differential_expression.csv
File already exist: GLDS-437_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-44_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-450_array_differential_expression.csv
Downloading: GLDS-455_array_differential_expression_GLmicroarray.csv
Downloading: GLDS-46_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-462_rna_seq_differential_expression_totRNA_GLbulkRNAseq.csv
File already exist: GLDS-463_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-464_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-467_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-469_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-47_Gwgbs_differential_methylation_tiles_GLMethylSeq.csv
File already exist: GLDS-47_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-476_rna_seq_differential_expression.csv
File already exist: GLDS-48_Gwgbs_differential_methylation_tiles_GLMethylSeq.csv
Downloading: GLDS-48_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-49_rna_seq_differential_expression.csv
File already exist: GLDS-498_rna_seq_differential_expression.csv
Downloading: GLDS-50_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-50_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-502_rna_seq_differential_expression.csv
File already exist: GLDS-506_rna_seq_differential_expression_GLbulkRNAseq.csv
Downloading: GLDS-508_rna_seq_differential_expression.csv
File already exist: GLDS-510_rna_seq_differential_expression.csv
File already exist: GLDS-511_rna_seq_differential_expression.csv
File already exist: GLDS-512_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-513_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-514_rna-seq_differential_expression.csv
File already exist: GLDS-514_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-515_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-516_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-518_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-519_rna_seq_differential_expression.csv
Downloading: GLDS-52_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-52_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-525_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-539_rna_seq_differential_expression.csv
File already exist: GLDS-540_rna_seq_differential_expression.csv
File already exist: GLDS-542_array_differential_expression.csv
File already exist: GLDS-546_array_differential_expression.csv
File already exist: GLDS-547_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-548_array_differential_expression.csv
File already exist: GLDS-556_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-557_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-568_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-569_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-558_rna_seq_differential_expression.csv
File already exist: GLDS-567_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-570_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-573_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-573_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-577_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-596_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-6_array_differential_expression_GLmicroarray.csv
Downloading: GLDS-586_rna-seq_differential_expression.csv
Skipping file: GLDS-586_rna-seq_differential_expression.csv. No data after filtering.
Downloading: GLDS-61_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-61_array_differential_expression_GLmicroarray.csv. No data after filtering.
Downloading: GLDS-587_rna-seq_differential_expression.csv
Skipping file: GLDS-587_rna-seq_differential_expression.csv. No data after filtering.
File already exist: GLDS-588_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-589_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-62_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-608_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-603_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-604_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-605_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-606_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-612_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-615_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-617_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-621_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-620_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-70_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-638_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-641_rna_seq_differential_expression_GLbulkRNAseq.csv
Downloading: GLDS-74_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-74_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-673_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-674_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-678_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-679_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-680_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-681_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-682_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-79_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-688_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-80_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-85_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-716_rna_seq_differential_expression_GLbulkRNAseq.csv
Downloading: GLDS-87_array_differential_expression_GLmicroarray.csv
Skipping file: GLDS-87_array_differential_expression_GLmicroarray.csv. No data after filtering.
File already exist: GLDS-720_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-91_rna_seq_differential_expression_GLbulkRNAseq.csv
File already exist: GLDS-92_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-93_array_differential_expression_GLmicroarray.csv
File already exist: GLDS-98_rna_seq_differential_expression.csv
File already exist: GLDS-99_rna_seq_differential_expression_GLbulkRNAseq.csv

In [18]:
manifest.head()

,identifier,technology,measurement,assay_name,taxonomy,organism,material,host_organism,host_taxonomy,host_strain,filename,url,differential_analysis_method
203,OSD-1,DNA microarray,transcription profiling,OSD-1_transcription-profiling_dna-microarray_A...,7227,Drosophila melanogaster,Whole Organism,,,,GLDS-1_array_differential_expression.csv,https://osdr.nasa.gov/geode-py/ws/studies/OSD-...,DESeq2
290,OSD-100,RNA Sequencing (RNA-Seq),transcription profiling,OSD-100_transcription-profiling_rna-sequencing...,10090,Mus musculus,left eye,,,,GLDS-100_rna_seq_differential_expression.csv,https://osdr.nasa.gov/geode-py/ws/studies/OSD-...,DESeq2
298,OSD-101,RNA Sequencing (RNA-Seq),transcription profiling,OSD-101_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left gastrocnemius,,,,GLDS-101_rna_seq_differential_expression_GLbul...,https://osdr.nasa.gov/geode-py/ws/studies/OSD-...,DESeq2
287,OSD-102,RNA Sequencing (RNA-Seq),transcription profiling,OSD-102_transcription-profiling_rna-sequencing...,10090,Mus musculus,Left kidney,,,,GLDS-102_rna_seq_differential_expression_GLbul...,https://osdr.nasa.gov/geode-py/ws/studies/OSD-...,DESeq2
286,OSD-103,Whole Genome Bisulfite Sequencing,DNA methylation profiling,OSD-103_dna-methylation-profiling_whole-genome...,10090,Mus musculus,Left quadriceps femoris,,,,GLDS-103_Gwgbs_differential_methylation_tiles_...,https://osdr.nasa.gov/geode-py/ws/studies/OSD-...,methylKit